name: flutter_midi_command_plus_example
description: "Demonstrates how to use the flutter_midi_command_plus plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: any
  bb_dart:
    git: https://github.com/aestesis/bb.dart.git
  bb.flutter:
    git: https://github.com/aestesis/bb.flutter.git

  flutter_midi_command_plus:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
